App/App.csproj
App/SelectedUniversity.Designer.cs
App/SelectedUniversity.cs
App/universities.Designer.cs
App/universities.cs

Added a few comments where the server calls are needed and what data has to be returned from db

Frontend universities form

---

App/FormManager.cs
App/UniversitySearchForm.Designer.cs
Dbo/DatabaseExecutor.cs
Dbo/Dbo.csproj
Dbo/Scripts/CreateReviewTable.txt
insertReviews.sql

Fixed reviews table and it's mentions in code

fixed reviews

---

App/App.csproj
App/ContainerBuilder.cs
App/FormManager.cs
App/Helpers/Helper.cs
App/LoginForm.Designer.cs
App/LoginForm.cs
App/Program.cs
App/Properties/AssemblyInfo.cs
App/Properties/Resources.Designer.cs
App/SignUpForm.Designer.cs
App/SignUpForm.cs
App/SignUpForm.resx
App/reviewForm.cs
Dbo/DatabaseExecutor.cs
RestApi/Controllers/AccountController.cs

Adding sign-up form. Changed Namespace from Objektinis to App since there were inconsistencies. in ContainerBulder changed one line because Form with parameters didn't launch correctly.
All tests are passed

Sign up form

---

AcceptanceTests/ServerSide_Should.cs
AcceptanceTests/TestFaculties.cs
App/App.csproj
App/FormManager.cs
App/LoginForm.Designer.cs
App/LoginForm.cs
App/SelectedUniversityForm.Designer.cs
App/SelectedUniversityForm.cs
App/SignUpForm.cs
App/UniversitySearchForm.Designer.cs
App/UniversitySearchForm.cs
App/readReview.Designer.cs
App/readReview.cs
App/reviewForm.Designer.cs
App/reviewForm.cs

* Some naming changes
* Some code cleanup
* Added password characters in LoginForm
* Added a check for whitespace password in SignUpForm

Cleanup and minor changes

---

App/FormManager.cs

Tests passed. Merging caused some inconsistencies

merge fixes

---

Dbo/DatabaseExecutor.cs

adding dbExecutor fixes

---

AppUnitTests/BaseFormManager_Should.cs
AppUnitTests/UniversitySearchFormManager_Should.cs
RestApi/Controllers/AccountController.cs
RestApiUnitTest/AccountController_Should.cs

Viskas ka mes galim istestuot metode

More tests

---

RestApiUnitTest/AccountController_Should.cs

Dar vienas one-lineris :)
Fixed duplicate test data

fixed one duplicate line

---

Web/Views/CreateAccount/Index.cshtml

Labels were associated with wrong input fields

html naming fix

---

Webserver.Tests/App.config
Webserver/App_Start/Startup.Auth.cs
Webserver/App_Start/UnityConfig.cs
Webserver/Controllers/AccountController.cs
Webserver/Controllers/FacultiesController.cs
Webserver/Controllers/ReviewsController.cs
Webserver/Controllers/UniversitiesController.cs
Webserver/Global.asax.cs
Webserver/Repositories/IUniversityRepository.cs
Webserver/Repositories/UniversityRepository.cs
Webserver/Views/Faculties/Details.cshtml
Webserver/Views/Faculties/Index.cshtml
Webserver/Views/Reviews/Details.cshtml
Webserver/Views/Reviews/Index.cshtml
Webserver/Views/Universities/Details.cshtml
Webserver/Views/Universities/Index.cshtml
Webserver/Webserver.csproj
Webserver/packages.config

* DI is now available. Define dependencies in `App_Start/UnityConfig.cs`
* Added UniversityController with following actions:
- Return list of universities (Index)
- Return details of specific university (Details)
- Return list of universities containing specific name (Search)
* Added UniversityRepository class for later use. (Database code should go there)
* Added ReviewsController with following actions:
- Return list of reviews (Index)
- Return details of specific review (Details)
* Added FacultyController with following actions:
- Return list of faculties for specified university (Index)
- Return details of specific faculty (Details)
* Some cleanups
///TODO: Ensure reviews are fetched for corresponding subject (same review controller for different types of reviews)

WIP: Implement Dependency Injection and couple of views

---

Webserver/Controllers/UniversityController.cs
Webserver/Data/ApplicationDbContext.cs
Webserver/Views/Shared/_Layout.cshtml
Webserver/Views/University/University.cshtml

Navigation bar pridėjau universities ir pašalinau dublikatinį home mygtuką

Doviles sandbox branch

---

Webserver/Controllers/FacultiesController.cs
Webserver/Controllers/ReviewsController.cs
Webserver/Controllers/UniversitiesController.cs
Webserver/Data/ApplicationDbContext.cs
Webserver/Data/Models/DataFixture.cs
Webserver/Views/Faculties/Details.cshtml
Webserver/Views/Faculties/Index.cshtml
Webserver/Views/Reviews/Faculty.cshtml
Webserver/Views/Reviews/University.cshtml
Webserver/Views/Universities/Details.cshtml
Webserver/Web.config
Webserver/Webserver.csproj

* Universities and faculties now get correct reviews
* Added navigation:
- University (Can check reviews / return to university list)
- Faculty (Can check reviews / return to selected university)
- Programme
* Moved database connection string to config file
* Added some test data to populate the views

Implement navigation logic in views

---

UniversityAdvisor.sln
WebScraper/App.config
WebScraper/Models/Account.cs
WebScraper/Models/Faculty.cs
WebScraper/Models/Programme.cs
WebScraper/Models/Review.cs
WebScraper/Models/University.cs
WebScraper/Program.cs
WebScraper/Properties/AssemblyInfo.cs
WebScraper/ScrapeFiles/AustriaUniversities.html
WebScraper/ScrapeFiles/IsraelUniversities.html
WebScraper/ScrapeFiles/LithuaniaUniversities.html
WebScraper/WebScraper.csproj
WebScraper/packages.config

Gathers:
- Universities
- Faculties
- University descriptions
- Programmes
Doesn't save any of it yet. Needs to connect to Database.

Web scraper v2

---

Models/Models.csproj
Models/Programme.cs
Models/Review.cs
Webserver/Controllers/AddReviewController.cs
Webserver/Controllers/ProgrammesController.cs
Webserver/Controllers/ReviewsController.cs
Webserver/Data/ApplicationDbContext.cs
Webserver/Data/Configuration/ProgrammeConfiguration.cs
Webserver/Data/Models/DataFixture.cs
Webserver/Data/Repositories/IProgrammeRepository.cs
Webserver/Data/Repositories/IRepository.cs
Webserver/Data/Repositories/ProgrammeRepository.cs
Webserver/Data/Repositories/RepositoryBase.cs
Webserver/Startup.cs
Webserver/Views/AddReview/FacultyReview.cshtml
Webserver/Views/AddReview/ProgrammeReview.cshtml
Webserver/Views/AddReview/UniversityReview.cshtml
Webserver/Views/Faculties/Details.cshtml
Webserver/Views/Programmes/Details.cshtml
Webserver/Views/Programmes/Index.cshtml
Webserver/Views/Reviews/Programme.cshtml
Webserver/Views/Universities/Details.cshtml
Webserver/Webserver.csproj

Added:
- Programme model
- Reviewing works for all entities
- Changed Review value type from string to int (hell yes, deleting databases again)
- value adding now works just kinda, leaving that for someone else to play with

Add review

---

Webserver/Controllers/ReviewsController.cs
Webserver/Data/Infrastructure/DatabaseFactory.cs
Webserver/Data/Infrastructure/IDatabaseFactory.cs
Webserver/Data/Repositories/ApplicationUserRepository.cs
Webserver/Startup.cs

* Removed some unnecessary imports
* Simplified codestyle
* `ApplicationDbContext` is now never injected by DI. Instead, `DatabaseFactory` providing the option to create `ApplicationDbContext` is injected as singleton

Follow database factory logic

---

Webserver/Content/star_rating.css
Webserver/Controllers/FacultiesController.cs
Webserver/Controllers/ProgrammesController.cs
Webserver/Controllers/UniversitiesController.cs
Webserver/Data/Repositories/IReviewRepository.cs
Webserver/Data/Repositories/ReviewRepository.cs
Webserver/Views/AddReview/FacultyReview.cshtml
Webserver/Views/AddReview/ProgrammeReview.cshtml
Webserver/Views/AddReview/UniversityReview.cshtml
Webserver/Views/Faculties/Details.cshtml
Webserver/Views/Faculties/Index.cshtml
Webserver/Views/Home/Index.cshtml
Webserver/Views/Programmes/Details.cshtml
Webserver/Views/Programmes/Index.cshtml
Webserver/Views/Reviews/Faculty.cshtml
Webserver/Views/Reviews/Programme.cshtml
Webserver/Views/Reviews/University.cshtml
Webserver/Views/Universities/Details.cshtml
Webserver/Views/Universities/Index.cshtml
Webserver/Webserver.csproj

- Unnecessary elements removed from UI
- Added charts

lots of little frontend changes, added charts

---

Webserver/Views/Faculties/Details.cshtml
Webserver/Views/Programmes/Details.cshtml
Webserver/Views/Universities/Details.cshtml

Buvo jau sumerge'inta bet kažkaip buvo ištrinti šitie pataisymai

transparent background and font color

---

WebScraper/Scraper.cs
WebScraper/Test.cs
Webserver.Tests/app.config
Webserver/App_Start/Startup.Auth.cs
Webserver/Startup.cs
Webserver/Web.config
Webserver/Web.universityadvisor - Web Deploy.config
Webserver/Webserver.csproj
Webserver/packages.config

* Scraper now works both in public host environment and local environment
* Project is now published on public host in AzurePortal as an app service `https://universityadvisor.azurewebsites.net/`
* Protected secrets and api keys from the public eye by moving them to AzurePortal configuration.
* Added a configuration file to modify web.config at runtime whenever publishing (to remove debug elements for example)
* Added Google external login through Google+ API (only works on published site though)

Add publishing config and google external authentication

---

Webserver/Controllers/ReviewsController.cs
Webserver/Controllers/UniversitiesController.cs
Webserver/Enums/Enums.cs
Webserver/Services/IPaginationHandler.cs
Webserver/Services/PaginationHandler.cs
Webserver/Startup.cs
Webserver/Views/Reviews/Delete.cshtml
Webserver/Views/Reviews/Details.cshtml
Webserver/Views/Reviews/Edit.cshtml
Webserver/Views/Reviews/Faculty.cshtml
Webserver/Views/Reviews/Programme.cshtml
Webserver/Views/Reviews/University.cshtml
Webserver/Views/Universities/Add.cshtml
Webserver/Views/Universities/Details.cshtml
Webserver/Views/Universities/Index.cshtml
Webserver/Webserver.csproj

* Refactored pagination logic into more reusable code
* Added pagination for reviews

Pagination follow-up

---

Webserver/Views/AddReview/FacultyReview.cshtml
Webserver/Views/AddReview/ProgrammeReview.cshtml
Webserver/Views/AddReview/UniversityReview.cshtml

Placeholder tekstas rašant review

placeholder text for review
